require 'cloud_access/ec2/describe/instance'
require 'cloud_access/ec2/describe/instances'
require 'cloud_access/ec2/describe/snapshot'
require 'cloud_access/ec2/describe/snapshots'
require 'cloud_access/ec2/describe/volume'
require 'cloud_access/ec2/describe/volumes'
